### ISSUE TITLE
Invalid postisntall script

### ISSUE THREAD

**Issue by Mister-Hope** [jerrywu001/sandpack-vue3#11]
Hi, a basic is that postinstall runs both when:

- Installing deps in source code repo 
- Installing the dep at any repo

The latest version adds a postinstall calling `rimraf`, but users are likely not install this module globally, or do not have the bin:

https://github.com/jerrywu001/sandpack-vue3/blob/81e3e364c2d23273a41be73dfd4007fa55f04550/package.json#L72

So that an error will be thrown once users install this pkg:

https://github.com/vuepress-theme-hope/vuepress-theme-hope/actions/runs/7643843159/job/20826807099#step:5:26

Please move the logic to `prepare` so that the command only runs when installing at source repo.

A new version is needed as this is a critical bug which stops almost every user installing latest version

**Comment by Mister-Hope** [comment]
Also I am pretty annoyed about the careless commit msg among the timeline, it confuse other people, and at least, it spoils my mood to raise a pr and contribute to this project.

The commit causing this is: https://github.com/jerrywu001/sandpack-vue3/commit/fcd73e8459798f0fa06417a870aae1bf357db287 and you'd better check why you need to "delete react types manually"

**Comment by jerrywu001** [comment]
对不起，大佬，我错了，马上到公司就改过来🏃🏃🏃

**Comment by jerrywu001** [comment]
给大佬添麻烦了，已发布新版本
