### ISSUE TITLE
How to install your package ?

### ISSUE THREAD

**Issue by Andy-d-g** [jerrywu001/sandpack-vue3#7]
Hello, I try to install your package but I don't success.

## Context

- Vue3 (3.2.47)
- Vite (3.1.2)
- Node (18.16.3)

## Steps

1. yarn add sandpack-vue3
2. Add the dependancy into main.ts (`import SanpackPlugin from "sandpack-vue3";` + `app.use(SanpackPlugin());`)
3. Add into types of tsconfig.json : `"sandpack-vue3/global"`

## Error

```sh
Internal server error: Failed to resolve import "sandpack-vue3" from "src/main.ts". Does the file exist?
```

Thank you

**Comment by jerrywu001** [comment]
can you provide a github repo？

**Comment by Andy-d-g** [comment]
My bad, it was an issue with my monorepo.
